### PR TITLE
move walkPackageDependencyTree to if condition.

### PR DESCRIPTION
**Pull request by Raag007**
This is will fix issue related to this type of errors "Unable to resolve package fsevents error (While using this tool from Windows)"
Issue: https://github.com/christopherthielen/check-peer-dependencies/issues/4

### CODE REVIEW

**Comment by Raag007** [comment]
@christopherthielen can you please review and approve these changes.

**Comment by christopherthielen** [comment]
I'm on holiday for 2 weeks. Will take a look when I'm back in September.

**Comment by Raag007** [comment]
> I'm on holiday for 2 weeks. Will take a look when I'm back in September.

Got it, take care.

**Comment by Raag007** [comment]
> I'm on holiday for 2 weeks. Will take a look when I'm back in September.

Hello, can you please take a look at this and help here.

**Comment by christopherthielen** [comment]
Heads up: I reverted this change in https://github.com/christopherthielen/check-peer-dependencies/commit/25a89a7

Instead, we will only throw an error for missing dependencies if they are not found in `optionalDependencies`

**Pull request merged**
